apiVersion: v2
dependencies:
- condition: cass-operator.enabled
  name: cass-operator
  repository: file://../cass-operator
  version: 0.35.4
- condition: reaper-operator.enabled
  name: reaper-operator
  repository: file://../reaper-operator
  version: 0.32.3
- condition: medusa.enabled
  name: medusa-operator
  repository: file://../medusa-operator
  version: 0.32.0
- name: k8ssandra-common
  repository: file://../k8ssandra-common
  version: 0.28.5
- condition: kube-prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 20.0.1
deprecated: true
description: 'DEPRECATED please see https://github.com/k8ssandra/k8ssandra-operator Provisions and configures an instance of the entire K8ssandra stack. This includes Apache Cassandra, Stargate, Reaper, Medusa, Prometheus, and Grafana. '
home: https://k8ssandra.io/
maintainers:
- email: k8ssandra-developers@googlegroups.com
  name: K8ssandra Team
  url: https://github.com/k8ssandra
name: k8ssandra
sources:
- https://github.com/k8ssandra/k8ssandra
- https://github.com/k8ssandra/k8ssandra/tree/main/charts/k8ssandra
type: application
version: 1.5.2
