apiVersion: v2
description: 'Creates a CassandraBackup custom resource instance. This chart should
  be used in conjunction with the Medusa Operator chart. '
home: https://k8ssandra.io/
maintainers:
- email: k8ssandra-developers@googlegroups.com
  name: K8ssandra Team
  url: https://github.com/k8ssandra
name: backup
sources:
- https://github.com/k8ssandra/medusa-operator
- https://github.com/k8ssandra/k8ssandra/tree/main/charts/backup
type: application
version: 0.26.0
